### ISSUE TITLE
Export Escape

### ISSUE THREAD

**Issue by defunkt** [pvande/Milk#1]
It can be useful in Views.

**Comment by pvande** [comment]
Is the goal that this function should be replaceable, or simply exported for general utility?

**Comment by defunkt** [comment]
Maybe a little bit of both.

**Comment by pvande** [comment]
Try out the changes in 718711b8e2fcef9da3e0; I think you'll like them.

**Comment by pvande** [comment]
Hmm...  Can't make out why that SHA didn't autolink.  Anyhow, it's the current HEAD of `master`.

**Comment by defunkt** [comment]
Awesome!

(Only full SHAs autolink)
