### ISSUE TITLE
render

### ISSUE THREAD

**Issue by cj** [pvande/Milk#6]
Hi,

So when I do

```
       "name": "Tater",
       "bolder": function() {
          return function(text, render) {
            return "<b>" + render(text) + '</b>'
          }
       }
```

render says it's false and not a function... any ideas?

Many thanks

**Comment by cj** [comment]
Made an example below of it not working...

http://pvande.net/Milk/playground.html?data=header%3A%20%22Colors%22%0Atest%3A%20-%3E%0A%20%20(text%2C%20render)%20-%3E%0A%20%20%20%20render%20text%0Alist%3A%20%5B%0A%20%20{%20name%3A%20%22red%22%2C%20%20%20url%3A%20%22%23Red%22%2C%20%20%20current%3A%20yes%20}%0A%20%20{%20name%3A%20%22green%22%2C%20url%3A%20%22%23Green%22%2C%20current%3A%20no%20%20}%0A%20%20{%20name%3A%20%22blue%22%2C%20%20url%3A%20%22%23Blue%22%2C%20%20current%3A%20no%20%20}%0A%5D&tmpl=%3Ch1%3E{{header}}%3C%2Fh1%3E%0A{{%23list.length}}%0A%20%20%3Cul%3E%0A%20%20{{%23list}}%0A%20%20%20%20{{%23current}}%0A%20%20%20%20%20%20%3Cli%3E%3Cstrong%3E{{%23test}}{{name}}{{%2Ftest}}%3C%2Fstrong%3E%3C%2Fli%3E%0A%20%20%20%20{{%2Fcurrent}}%0A%20%20%20%20{{^current}}%0A%20%20%20%20%20%20%3Cli%3Ea%20href%3D%22{{url}}%22%3E{{name}}%3C%2Fa%3E%3C%2Fli%3E%0A%20%20%20%20{{%2Fcurrent}}%0A%20%20{{%2Flist}}%0A%20%20%3C%2Ful%3E%0A{{%2Flist.length}}%0A{{^list.length}}%0A%20%20%3Cp%3EThe%20list%20is%20empty.%3C%2Fp%3E%0A{{%2Flist.length}}

**Comment by pvande** [comment]
As per the spec, lambda results are automatically rendered against the current context.  Milk does not pass a render function.

http://bit.ly/qWzf0c

(Incidentally, the only difference between `function() { return function() { ... } }` and `function() { ... }` in Milk is the value of `this` -- both receive the raw template as a string.)

**Comment by cj** [comment]
but you then you just have access to {{header}} and not Colors so how would I make a lambda that would allow me to do lambda: (raw) -> "#{raw.toLowerCase()}" ?  With mustache the javascript version they parse the render function as the second param allowing you render the raw value.....

**Comment by pvande** [comment]
[This](http://bit.ly/nvQYOc) works if you're looking up a property on the object containing the lambda.

[This](http://bit.ly/nGAcwI) works if you're looking up a property on or below the object containing the lambda.

Milk does not presently provide direct access to the current context stack to lambdas, either through an object, a lookup function, or a render function -- all three are arguably useful.  Mustache.js was (to my knowledge) the first to add the `render` argument to lambda calls; I don't know of any other Mustache implementations that provide it.

**Comment by cj** [comment]
Most of them actually give you access to render or even actually have the value rendered when it's passed to the lambda for example https://github.com/bobthecow/mustache.php

**Comment by cj** [comment]
Milk.render(raw, this) works.... is there a performance hit in doing that? (is there a reason we can pass that as the second param) ?

**Comment by cj** [comment]
^ method fails when using dot notation http://bit.ly/qq18R1

**Comment by pvande** [comment]
Passing the content in pre-rendered is specifically incorrect behavior, as per the spec.

There's no measurable performance hit to calling `Milk.render(raw, this)`; Milk caches parsed templates fairly aggressively.  You do, however, lose the context stack you've built up to this point and any custom delimiters you have set.

I'm disinclined to pass anything as a second parameter to lambdas until there is something concrete in the spec, and any solution there will likely have to address the more general issue of context lookups for arbitrary properties.

Having said all that: if you absolutely _cannot_ live without this functionality, and cannot wait for a better solution to come along, you can patch it in yourself.  (This code is provided as inspiration, and is not tested.)

```
# https://github.com/pvande/Milk/blob/master/milk.coffee#L165
-             tmpl  = if value instanceof Function then value(raw) else raw
+             args = arguments
+             tmpl  = if value instanceof Function then value(raw, (t) => Expand(this, t, args...)) else raw
```

**Comment by pvande** [comment]
As for why it fails with dotted names, the `this` reference is the object the lambda is declared on, which has no `header` property.  This is as per the caveat I described.

**Comment by cj** [comment]
Ye so you would do http://bit.ly/p9Usvv ...... thank you I'll give it a try.....

**Comment by cj** [comment]
I just want to use Milk because according to these tests I setup http://jsperf.com/jquery-template-table-performance/13 it's faster than the rest :)

**Comment by cj** [comment]
ye mustache.js makes the this of any function called the object data used, mustache.coffee (milk) seems to use the this of the parent object of the function...

**Comment by pvande** [comment]
For more information on this, there's a discussion thread on the [spec](https://github.com/mustache/spec/issues/19).
